{
	"openapi": "3.0.1",
	"info": {
		"version": "2.0.2",
		"title": "E-Pharmacy API",
		"description": "The API for the E-Pharmacy project"
	},
	"import": {
		"type": "json"
	},
	"consumes": ["application/json"],
	"produces": ["application/json"],
	"servers": [
		{ "url": "http://localhost:4000/api" },
		{ "url": "https://e-pharmacy-v77l.onrender.com/api" }
	],
	"tags": [
		{
			"name": "Auth",
			"description": "Authorization"
		},
		{
			"name": "Dashboard",
			"description": "Dashboard data"
		},
		{
			"name": "Customers",
			"description": "Customers data"
		},
		{
			"name": "Orders",
			"description": "Orders data"
		},
		{
			"name": "Products",
			"description": "Products data"
		},
		{
			"name": "Suppliers",
			"description": "Suppliers data"
		}
	],

	"paths": {
		"/users/login": {
			"post": {
				"tags": ["Auth"],
				"summary": "User login",
				"parameters": [],
				"requestBody": {
					"description": "login object",
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/Login"
							}
						}
					}
				},
				"responses": {
					"201": {
						"description": "successfully login",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"token": {
											"type": "string",
											"example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NGIzNWI2MDA4MGFkNWY1ZmViZDVhMiIsImlhdCI6MTcxNjM4NDg5MCwiZXhwIjoxNzE2NDI4MDkwfQ.dI4QYUK9onyX6k8nqQoMMIlIePXN5kZr4M5nigrBwng"
										},
										"user": {
											"type": "object",
											"properties": {
												"id": {
													"type": "string",
													"example": "65cb32121b768ed2b321e4ea"
												},
												"name": {
													"type": "string",
													"example": "Eduard"
												},
												"email": {
													"type": "string",
													"example": "admin@gmail.com"
												}
											}
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "Unauthorized"
					}
				}
			}
		},
		"/users/logout": {
			"get": {
				"tags": ["Auth"],
				"summary": "User logout",
				"parameters": [],
				"security": [{ "Bearer": [] }],
				"responses": {
					"204": {
						"description": "No Content"
					},
					"401": {
						"description": "Unauthorized"
					},
					"500": {
						"description": "Internal Server Error"
					}
				}
			}
		},
		"/users/user-info": {
			"get": {
				"tags": ["Auth"],
				"summary": "Get user info",
				"parameters": [],
				"security": [{ "Bearer": [] }],
				"responses": {
					"201": {
						"description": "User info",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"id": {
											"type": "string",
											"example": "65cb32121b768ed2b321e4ea"
										},
										"name": {
											"type": "string",
											"example": "Eduard"
										},
										"email": {
											"type": "string",
											"example": "admin@gmail.com"
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "Unauthorized"
					},
					"500": {
						"description": "Internal Server Error"
					}
				}
			}
		},

		"/dashboard": {
			"get": {
				"tags": ["Dashboard"],
				"summary": "Get all data",
				"parameters": [],
				"security": [{ "Bearer": [] }],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"totalProducts": {
											"type": "string",
											"example": "1200"
										},
										"totalSuppliers": {
											"type": "string",
											"example": "130"
										},
										"totalCustomers": {
											"type": "string",
											"example": "110"
										},
										"customers": {
											"type": "array",
											"properties": {
												"_id": {
													"type": "string",
													"example": "664b2ea60080ad5f5febd495",
													"description": "id"
												},
												"photo": {
													"type": "string",
													"example": "https://i.imgur.com/1As0akH.png1",
													"description": "Url photo"
												},
												"name": {
													"type": "string",
													"example": "Nadia Ivanova",
													"description": "Name of customer"
												},
												"email": {
													"type": "string",
													"example": "nadia.ivanova@gmail.com",
													"description": "Email of customer"
												},
												"spent": {
													"type": "string",
													"example": "2,300.50",
													"description": "Spent"
												},
												"phone": {
													"type": "string",
													"example": "+380707614324",
													"description": "Phone of customer"
												},
												"address": {
													"type": "string",
													"example": "Obolon, Bldg. 10, Apt. 45",
													"description": "Address of customer"
												},
												"register_date": {
													"type": "string",
													"example": "Mar 1, 2024",
													"description": "Register date of customer"
												}
											},
											"example": [
												{
													"_id:": "664b2ea60080ad5f5febd495",
													"photo": "https://i.imgur.com/1As0akH.png1",
													"name": "Nadia Ivanova",
													"email": "nadia.ivanova@gmail.com",
													"spent": "2,300.50",
													"phone": "+380707614324",
													"address": "Obolon, Bldg. 10, Apt. 45",
													"register_date": "Mar 1, 2024"
												}
											]
										},
										"income_expenses": {
											"type": "array",
											"properties": {
												"_id": {
													"type": "string",
													"example": "664b2ea60080ad5f5febd495",
													"description": "id"
												},
												"name": {
													"type": "string",
													"example": "Market Cap Ltd",
													"description": "Name"
												},
												"amount": {
													"type": "string",
													"example": "+1,200.88",
													"description": "Amount"
												},
												"type": {
													"type": "string",
													"example": "Income",
													"description": "Type"
												}
											},
											"example": [
												{
													"_id:": "664b2ea60080ad5f5febd495",
													"name": "Market Cap Ltd",
													"amount": "+1,200.88",
													"type": "Income"
												}
											]
										}
									}
								}
							}
						}
					},
					"401": {
						"description": "Unauthorized"
					}
				}
			}
		},

		"/customers": {
			"get": {
				"tags": ["Customers"],
				"summary": "Get all customers",
				"parameters": [
					{
						"name": "sortBy",
						"in": "query",
						"description": "Field to sort by",
						"required": false,
						"schema": {
							"type": "string",
							"default": "name"
						}
					},
					{
						"name": "reverse",
						"in": "query",
						"description": "Sort direction (0 for ascending, 1 for descending)",
						"required": false,
						"schema": {
							"type": "integer",
							"enum": [0, 1],
							"default": 0
						}
					},
					{
						"name": "nameCustomer",
						"in": "query",
						"description": "Filter customers by name",
						"required": false,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "page",
						"in": "query",
						"description": "Current page",
						"required": false,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "perPage",
						"in": "query",
						"description": "Count items in page ",
						"required": false,
						"schema": {
							"type": "string"
						}
					}
				],
				"security": [{ "Bearer": [] }],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"properties": {
										"_id": {
											"type": "string",
											"example": "664b2ea60080ad5f5febd495",
											"description": "id"
										},
										"photo": {
											"type": "string",
											"example": "https://i.imgur.com/1As0akH.png1",
											"description": "Url photo"
										},
										"name": {
											"type": "string",
											"example": "Nadia Ivanova",
											"description": "Name of customer"
										},
										"email": {
											"type": "string",
											"example": "nadia.ivanova@gmail.com",
											"description": "Email of customer"
										},
										"spent": {
											"type": "string",
											"example": "2,300.50",
											"description": "Spent"
										},
										"phone": {
											"type": "string",
											"example": "+380707614324",
											"description": "Phone of customer"
										},
										"address": {
											"type": "string",
											"example": "Obolon, Bldg. 10, Apt. 45",
											"description": "Address of customer"
										},
										"register_date": {
											"type": "string",
											"example": "Mar 1, 2024",
											"description": "Register date of customer"
										}
									}
								},
								"example": [
									{
										"_id:": "664b2ea60080ad5f5febd495",
										"photo": "https://i.imgur.com/1As0akH.png1",
										"name": "Nadia Ivanova",
										"email": "nadia.ivanova@gmail.com",
										"spent": "2,300.50",
										"phone": "+380707614324",
										"address": "Obolon, Bldg. 10, Apt. 45",
										"register_date": "Mar 1, 2024"
									}
								]
							}
						}
					}
				},
				"401": {
					"description": "Unauthorized"
				}
			},
			"/customers/{customerId}": {
				"get": {
					"tags": ["Customers"],
					"summary": "Get a customer by id",
					"parameters": [
						{
							"name": "customerId",
							"in": "path",
							"required": true,
							"schema": {
								"type": "string"
							},
							"description": "The ID of the customer"
						}
					],
					"security": [{ "Bearer": [] }],
					"responses": {
						"200": {
							"description": "OK",
							"content": {
								"application/json": {
									"schema": {
										"type": "object",
										"properties": {
											"_id": {
												"type": "string",
												"example": "664b2ea60080ad5f5febd495",
												"description": "id"
											},
											"photo": {
												"type": "string",
												"example": "https://i.imgur.com/1As0akH.png1",
												"description": "Url photo"
											},
											"name": {
												"type": "string",
												"example": "Nadia Ivanova",
												"description": "Name of customer"
											},
											"email": {
												"type": "string",
												"example": "nadia.ivanova@gmail.com",
												"description": "Email of customer"
											},
											"spent": {
												"type": "string",
												"example": "2,300.50",
												"description": "Spent"
											},
											"phone": {
												"type": "string",
												"example": "+380707614324",
												"description": "Phone of customer"
											},
											"address": {
												"type": "string",
												"example": "Obolon, Bldg. 10, Apt. 45",
												"description": "Address of customer"
											},
											"register_date": {
												"type": "string",
												"example": "Mar 1, 2024",
												"description": "Register date of customer"
											}
										}
									},
									"example": {
										"_id:": "664b2ea60080ad5f5febd495",
										"photo": "https://i.imgur.com/1As0akH.png1",
										"name": "Nadia Ivanova",
										"email": "nadia.ivanova@gmail.com",
										"spent": "2,300.50",
										"phone": "+380707614324",
										"address": "Obolon, Bldg. 10, Apt. 45",
										"register_date": "Mar 1, 2024"
									}
								}
							}
						}
					},
					"400": {
						"description": "_id is not valid id"
					}
				}
			}
		},
		"/customers/{customerId}": {
			"get": {
				"tags": ["Customers"],
				"summary": "Get a customer by id",
				"parameters": [
					{
						"name": "customerId",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"description": "The ID of the customer"
					}
				],
				"security": [{ "Bearer": [] }],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"_id": {
											"type": "string",
											"example": "664b2ea60080ad5f5febd495",
											"description": "id"
										},
										"photo": {
											"type": "string",
											"example": "https://i.imgur.com/1As0akH.png1",
											"description": "Url photo"
										},
										"name": {
											"type": "string",
											"example": "Nadia Ivanova",
											"description": "Name of customer"
										},
										"email": {
											"type": "string",
											"example": "nadia.ivanova@gmail.com",
											"description": "Email of customer"
										},
										"spent": {
											"type": "string",
											"example": "2,300.50",
											"description": "Spent"
										},
										"phone": {
											"type": "string",
											"example": "+380707614324",
											"description": "Phone of customer"
										},
										"address": {
											"type": "string",
											"example": "Obolon, Bldg. 10, Apt. 45",
											"description": "Address of customer"
										},
										"register_date": {
											"type": "string",
											"example": "Mar 1, 2024",
											"description": "Register date of customer"
										}
									}
								},
								"example": {
									"_id:": "664b2ea60080ad5f5febd495",
									"photo": "https://i.imgur.com/1As0akH.png1",
									"name": "Nadia Ivanova",
									"email": "nadia.ivanova@gmail.com",
									"spent": "2,300.50",
									"phone": "+380707614324",
									"address": "Obolon, Bldg. 10, Apt. 45",
									"register_date": "Mar 1, 2024"
								}
							}
						}
					}
				},
				"400": {
					"description": "_id is not valid id"
				}
			}
		},

		"/orders": {
			"get": {
				"tags": ["Orders"],
				"summary": "Get all orders",
				"parameters": [
					{
						"name": "sortBy",
						"in": "query",
						"description": "Field to sort by",
						"required": false,
						"schema": {
							"type": "string",
							"default": "name"
						}
					},
					{
						"name": "reverse",
						"in": "query",
						"description": "Sort direction (0 for ascending, 1 for descending)",
						"required": false,
						"schema": {
							"type": "integer",
							"enum": [0, 1],
							"default": 0
						}
					},
					{
						"name": "nameOrder",
						"in": "query",
						"description": "Filter orders by name",
						"required": false,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "page",
						"in": "query",
						"description": "Current page",
						"required": false,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "perPage",
						"in": "query",
						"description": "Count items in page ",
						"required": false,
						"schema": {
							"type": "string"
						}
					}
				],
				"security": [{ "Bearer": [] }],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"type": "object",
										"properties": {
											"_id": {
												"type": "string",
												"example": "65cb32121b768ed2b321e4ea"
											},
											"name": {
												"type": "string",
												"example": "task"
											},
											"text": {
												"type": "string",
												"example": "go to"
											},
											"deadline": {
												"type": "Number"
											},
											"priority": {
												"type": "string",
												"example": "without"
											},
											"columnId": {
												"type": "string",
												"example": "65cb76b2554c359c6c79b7cb"
											},
											"owner": {
												"type": "object",
												"properties": {
													"_id": {
														"type": "string",
														"example": "65c1588b623ec1693c4a6a1e"
													}
												}
											}
										},
										"required": [
											"_id",
											"name",
											"columnId",
											"priority",
											"deadline",
											"text",
											"owner"
										]
									}
								}
							}
						}
					}
				}
			}
		},

		"/products": {
			"get": {
				"tags": ["Products"],
				"summary": "Get all products",
				"parameters": [
					{
						"name": "sortBy",
						"in": "query",
						"description": "Field to sort by",
						"required": false,
						"schema": {
							"type": "string",
							"default": "name"
						}
					},
					{
						"name": "reverse",
						"in": "query",
						"description": "Sort direction (0 for ascending, 1 for descending)",
						"required": false,
						"schema": {
							"type": "integer",
							"enum": [0, 1],
							"default": 0
						}
					},
					{
						"name": "nameProduct",
						"in": "query",
						"description": "Filter products by name",
						"required": false,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "page",
						"in": "query",
						"description": "Current page",
						"required": false,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "perPage",
						"in": "query",
						"description": "Count items in page ",
						"required": false,
						"schema": {
							"type": "string"
						}
					}
				],
				"security": [{ "Bearer": [] }],
				"responses": {
					"200": {
						"description": "A list of products",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"$ref": "#/components/schemas/Product"
									}
								}
							}
						}
					}
				}
			},
			"post": {
				"tags": ["Products"],
				"summary": "Create a new product",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/Product"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Product created successfully",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"name": {
											"type": "string",
											"example": "pavlo"
										},
										"boarderId": {
											"type": "string",
											"example": "65cb32121b768ed2b321e4ea"
										},
										"owner": {
											"type": "string",
											"example": "65c1588b623ec1693c4a6a1e",
											"description": "Owner's user ID"
										},
										"_id": {
											"type": "string",
											"example": "65cb65e681cdb00ebc7fac94",
											"description": "Board ID"
										}
									}
								}
							}
						}
					}
				},
				"security": [
					{
						"Bearer": []
					}
				]
			}
		},
		"/products/{productId}": {
			"put": {
				"tags": ["Products"],
				"summary": "Edit product by id",
				"parameters": [
					{
						"name": "productId",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"description": "The ID of the product"
					}
				],
				"security": [{ "Bearer": [] }],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"_id": {
											"type": "string",
											"example": "65cb32121b768ed2b321e4ea"
										},
										"name": {
											"type": "string",
											"example": "pas"
										},
										"boarderId": {
											"type": "string",
											"example": "65cb32121b768ed2b321e4ea"
										},
										"owner": {
											"type": "string",
											"example": "65c1588b623ec1693c4a6a1e"
										}
									},
									"required": ["_id", "name", "boarderId", "owner"]
								}
							}
						}
					},
					"400": {
						"description": "_id is not valid id"
					}
				}
			}
		},

		"/suppliers": {
			"get": {
				"tags": ["Suppliers"],
				"summary": "Get all user suppliers",
				"parameters": [
					{
						"name": "sortBy",
						"in": "query",
						"description": "Field to sort by",
						"required": false,
						"schema": {
							"type": "string",
							"default": "name"
						}
					},
					{
						"name": "reverse",
						"in": "query",
						"description": "Sort direction (0 for ascending, 1 for descending)",
						"required": false,
						"schema": {
							"type": "integer",
							"enum": [0, 1],
							"default": 0
						}
					},
					{
						"name": "nameSupplier",
						"in": "query",
						"description": "Filter suppliers by name",
						"required": false,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "page",
						"in": "query",
						"description": "Current page",
						"required": false,
						"schema": {
							"type": "string"
						}
					},
					{
						"name": "perPage",
						"in": "query",
						"description": "Count items in page ",
						"required": false,
						"schema": {
							"type": "string"
						}
					}
				],
				"security": [{ "Bearer": [] }],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "array",
									"items": {
										"type": "object",
										"properties": {
											"_id": {
												"type": "string",
												"example": "65cb32121b768ed2b321e4ea"
											},
											"name": {
												"type": "string",
												"example": "pas"
											},
											"boarderId": {
												"type": "string",
												"example": "65cb32121b768ed2b321e4ea"
											},
											"owner": {
												"type": "object",
												"properties": {
													"_id": {
														"type": "string",
														"example": "65c1588b623ec1693c4a6a1e"
													}
												}
											}
										},
										"required": ["_id", "name", "boarderId", "owner"]
									}
								}
							}
						}
					}
				}
			},
			"post": {
				"tags": ["Suppliers"],
				"summary": "Create a new supplier",
				"requestBody": {
					"required": true,
					"content": {
						"application/json": {
							"schema": {
								"$ref": "#/components/schemas/ColumnPost"
							}
						}
					}
				},
				"responses": {
					"200": {
						"description": "Supplier created successfully",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"name": {
											"type": "string",
											"example": "pavlo"
										},
										"boarderId": {
											"type": "string",
											"example": "65cb32121b768ed2b321e4ea"
										},
										"owner": {
											"type": "string",
											"example": "65c1588b623ec1693c4a6a1e",
											"description": "Owner's user ID"
										},
										"_id": {
											"type": "string",
											"example": "65cb65e681cdb00ebc7fac94",
											"description": "Board ID"
										}
									}
								}
							}
						}
					}
				},
				"security": [
					{
						"Bearer": []
					}
				]
			}
		},
		"/suppliers/{supplierId}": {
			"put": {
				"tags": ["Suppliers"],
				"summary": "Get a supplier by supplierId",
				"parameters": [
					{
						"name": "supplierId",
						"in": "path",
						"required": true,
						"schema": {
							"type": "string"
						},
						"description": "The ID of the supplier"
					}
				],
				"security": [{ "Bearer": [] }],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"application/json": {
								"schema": {
									"type": "object",
									"properties": {
										"_id": {
											"type": "string",
											"example": "65cb32121b768ed2b321e4ea"
										},
										"name": {
											"type": "string",
											"example": "pas"
										},
										"boarderId": {
											"type": "string",
											"example": "65cb32121b768ed2b321e4ea"
										},
										"owner": {
											"type": "string",
											"example": "65c1588b623ec1693c4a6a1e"
										}
									},
									"required": ["_id", "name", "boarderId", "owner"]
								}
							}
						}
					},
					"400": {
						"description": "_id is not valid id"
					}
				}
			}
		}
	},
	"components": {
		"schemas": {
			"Login": {
				"type": "object",
				"properties": {
					"email": {
						"type": "string",
						"example": "qq@qq.qq"
					},
					"password": {
						"type": "string",
						"example": "Aqwerty"
					}
				}
			},
			"Customer": {
				"type": "object",
				"properties": {
					"_id": {
						"type": "string",
						"example": "664b2ea60080ad5f5febd495",
						"description": "id"
					},
					"photo": {
						"type": "string",
						"example": "https://i.imgur.com/1As0akH.png1",
						"description": "Url photo"
					},
					"name": {
						"type": "string",
						"example": "Nadia Ivanova",
						"description": "Name of customer"
					},
					"email": {
						"type": "string",
						"example": "nadia.ivanova@gmail.com",
						"description": "Email of customer"
					},
					"spent": {
						"type": "number",
						"example": "2,300.50",
						"description": "Spent"
					},
					"phone": {
						"type": "string",
						"example": "+380707614324",
						"description": "Phone of customer"
					},
					"address": {
						"type": "string",
						"example": "Obolon, Bldg. 10, Apt. 45",
						"description": "Address of customer"
					},
					"register_date": {
						"type": "string",
						"example": "Mar 1, 2024",
						"description": "Register date of customer"
					}
				}
			},
			"Order": {
				"type": "object",
				"properties": {
					"_id": {
						"type": "string",
						"example": "664b2ea60080ad5f5febd495",
						"description": "id"
					},
					"photo": {
						"type": "string",
						"example": "https://i.imgur.com/1As0akH.png1",
						"description": "Url photo"
					},
					"name": {
						"type": "string",
						"example": "Taras Shevchenko",
						"description": "Name of client"
					},
					"address": {
						"type": "string",
						"example": "Khreshchatyk, Bldg. 51, Apt. 137",
						"description": "Address of client"
					},
					"products": {
						"type": "number",
						"example": "12",
						"description": "Quantity products"
					},
					"price": {
						"type": "number",
						"example": "145",
						"description": "Price"
					},
					"status": {
						"type": "string",
						"example": "Complected",
						"description": "Status order"
					},
					"order_date": {
						"type": "string",
						"example": "July 31, 2023",
						"description": "Order date"
					}
				}
			},
			"Product": {
				"type": "object",
				"properties": {
					"_id": {
						"type": "string",
						"example": "664b2ea60080ad5f5febd495",
						"description": "id"
					},
					"photo": {
						"type": "string",
						"example": "https://i.ibb.co/bLKP624/5-15-1000x1000-min.jpg",
						"description": "Url photo"
					},
					"name": {
						"type": "string",
						"example": "Aspirin",
						"description": "Name of product"
					},
					"suppliers": {
						"type": "string",
						"example": "Square",
						"description": "Suppliers"
					},
					"stock": {
						"type": "number",
						"example": "12",
						"description": "Quantity in stock"
					},
					"price": {
						"type": "number",
						"example": "145",
						"description": "Price"
					},
					"category": {
						"type": "string",
						"example": "Medicine",
						"description": "Category"
					}
				}
			},
			"Supplier": {
				"type": "object",
				"properties": {
					"_id": {
						"type": "string",
						"example": "664b2ea60080ad5f5febd495",
						"description": "id"
					},
					"name": {
						"type": "string",
						"example": "Aspirin",
						"description": "Name of product"
					},
					"address": {
						"type": "string",
						"example": "Obolon, Bldg. 10, Apt. 45",
						"description": "Address of supplier"
					},
					"suppliers": {
						"type": "string",
						"example": "Square",
						"description": "Suppliers"
					},
					"date": {
						"type": "string",
						"example": "Mar 1, 2024",
						"description": "Date of supplier"
					},
					"amount": {
						"type": "number",
						"example": "6952.53",
						"description": "Amount"
					},
					"status": {
						"type": "string",
						"example": "Active",
						"description": "Status"
					}
				}
			},
			"Income-expense": {
				"type": "object",
				"properties": {
					"_id": {
						"type": "string",
						"example": "664b2ea60080ad5f5febd495",
						"description": "id"
					},
					"name": {
						"type": "string",
						"example": "Market Cap Ltd",
						"description": "Name"
					},
					"amount": {
						"type": "number",
						"example": "+1,200.88",
						"description": "Amount"
					},
					"type": {
						"type": "string",
						"example": "Income",
						"description": "Type"
					}
				}
			}
		},
		"securitySchemes": {
			"Bearer": {
				"type": "http",
				"scheme": "bearer",
				"bearerFormat": "JWT",
				"description": "Enter JWT token obtained after logging in"
			}
		}
	},
	"securityDefinitions": {
		"Bearer": {
			"type": "apiKey",
			"name": "Authorization",
			"in": "header"
		}
	},
	"host": "virtserver.swaggerhub.com",
	"schemes": ["https"]
}
